Repository lucantdel/decide-part-rivera, pull requests merged in 2023-12, with the labels that each got.

#44 Davdancab/13 aplicar algoritmo dhondt
  decide/voting/models.py
  decide/voting/tests.py
Labels: bug

#51 Jaigargar1/1 exportacion importacion censo xml
  decide/census/test_files/locustfile.py
  decide/census/tests.py
Labels: bug

#57 Lucantdel/26 GitHub actions
  .github/workflows/django.yml
  check_commit_format.sh
Labels: enhancement, configuration

#60 fix: arreglado votar por id
  decide/booth/views.py
Labels: bug

#61 fix: comprobar mensajes commit #26
  check_commit_format.sh
Labels: bug

#56 conf: actualizar requirements y plantilla issues #55
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  requirements.txt
Labels: configuration

#58 Guigomrom/38 reusar censos
  decide/census/admin.py
  decide/census/forms.py
  decide/census/migrations/0004_alter_census_city.py
  decide/census/models.py
  decide/census/templates/census/index.html
  decide/census/templates/reuse.html
  decide/census/tests.py
  decide/census/views.py
Labels: bug

#62 feat: test de interfaz reusar y index
  decide/census/test_selenium.py
Labels: enhancement

#64 Lucantdel/4 importacion exportacion censo csv
  decide/census/migrations/0001_initial.py
  decide/census/templates/export_csv.html
  decide/census/test_files/census_with_duplicates.csv
  decide/census/test_files/valid_census.csv
  decide/census/test_selenium.py
  decide/census/tests.py
  decide/census/views.py
  decide/decide/settings.py
  loadtest/locustfile.py
Labels: enhancement

#71 conf: Docker #70
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
Labels: configuration

#73 Mannavsic/5 borrado dhont url
  decide/booth/urls.py
  decide/booth/views.py
  decide/postproc/models.py
  decide/postproc/tests.py
  decide/postproc/views.py
  decide/voting/migrations/0005_voting_campo_personalizable.py
  decide/voting/migrations/0005_voting_number_seats_voting_postproc_type.py
  decide/voting/migrations/0006_merge_20231204_1058.py
  decide/voting/models.py
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
Labels: bug

#74 fix: Documento borrado
  doc/diario-de-equipo.md
Labels: documentation

#76 Mannavsic/66 pregunta multirrespuesta
  decide/booth/templates/booth/booth.html
  decide/booth/tests_selenium.py
  decide/store/tests.py
  decide/store/views.py
  decide/voting/admin.py
  decide/voting/migrations/0005_question_type.py
  decide/voting/migrations/0006_alter_question_type.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
Labels: enhancement

#79 Jaigargar1/1 exportacion importacion censo xml
  decide/census/templates/export_xml.html
  decide/census/tests.py
  decide/census/views.py
Labels: bug

#81 test: interfaz y carga xml
  decide/census/test_files/locustfile.py
  decide/census/test_selenium.py
  decide/census/tests.py
  loadtest/locustfile.py
Labels: test

#83 Lucantdel/26 GitHub actions
  .github/workflows/django.yml
  decide/decide/templates/inicio.html
Labels: enhancement, configuration
